language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: betabrain
  password:
    secure: sMriTxJRsGBaMcXJIvC455g8T2eJAEL64TeAMOes/UnyKTdza6QV5gF0xPSJ6+1QaQ1KDwUBtcIPiE+71me6v4i/qnYeF36ul9w3WuBtTt8RvsSBasf87in2Nvfnr+2ZYAUGfBVTKWiQz3CPbx9Erq1gRa7FIopeTfRa2xbjBgJ+dbVlCYUFWDaKOwpVmaeyS6MNBbEZEFCS/FJEZzBM1JfWOKzIvQhNqqIrCTqbXljdWrPFBeCCAzuXMYqwzjMC//Vee7K+9Lm06X4gguqQ0en0qXXEU8TxLATVSrd9byGK5oay/w/2K/TVpYrg4dy7YZKxSRpNLl/44EnskvcsczVD/Cx+VE5/gqMVwgB5fDkuy4kWqYSTBbTN806yjFPe0fQQ15i6Qz9wSJGU9BB7CR1MTDbeCDsnnP6w82VBVhWZ4hVFjQ4cifzbaY4OjrUXaclQSe3D4b0p7hmPRjCSiONX3IezAZB4NZipNFcOJrrR+O0N22mQLniLKD0ihWQ17u1NbgN/1qiTVOFFhbdSPDSm+iRZLA1Op2GfdRQzkZaZYeGiZ0+ZTxdoMEX+faI27rmVC0hZgtNaIwHB6ii2dKiPVu+0mxbbOWuGDkqdiVXMBUmJMkFabG12yMljXnh1maa5PQypMtsFUkgNBw66wig0/mtD98YjEvWE8H3iiWk=
  on:
    tags: true
    repo: digitalmensch/sqlf
    python: 3.6
